import { Button, FeatureCard, ProductCard, PricingCard, SectionHeader, TestimonialCard } from '@/components/ui';
import { FAQAccordion } from '@/components/FAQAccordion';
import { AnimatedBackground, HeroMockup, MetricCards } from '@/components/visuals';
import { pageMetadata } from '@/lib/seo';

export const metadata = pageMetadata('Northfield | Premium Website as a Service & Software Products', 'Northfield delivers premium Website as a Service packages, custom software, and modern business products.', '/');

export default function HomePage() {
  return <main className='relative overflow-hidden'><AnimatedBackground />
    <section className='section container-wrap'><div className='grid gap-10 lg:grid-cols-2 lg:items-center'><div><p className='mb-4 text-xs font-semibold uppercase tracking-[0.2em] text-emerald-500'>Northfield</p><h1 className='text-5xl font-semibold leading-tight md:text-6xl'>Premium digital systems for companies that want to move faster.</h1><p className='mt-6 text-lg text-slate-600 dark:text-slate-300'>We provide Website as a Service subscriptions and product-focused software development for modern businesses, field teams, and growing operators.</p><div className='mt-8 flex gap-4'><Button href='/contact'>Start a Project</Button><Button href='/pricing' variant='secondary'>See Monthly Packages</Button></div></div><HeroMockup /></div></section>
    <section className='section container-wrap'><MetricCards /></section>
    <section className='section container-wrap'><SectionHeader eyebrow='What we solve' title='From static websites to growth systems' sub='Northfield combines high-end design, performance, and monthly execution so your site and product presence keeps improving.'/><div className='grid gap-5 md:grid-cols-3'>{['Premium positioning','Faster launches','Predictable monthly support','Conversion-focused UX','Better trust with clients','Clean scalable code'].map(x=><FeatureCard key={x} title={x} text='Built with modern React and Next.js standards.'/>)}</div></section>
    <section className='section container-wrap'><SectionHeader eyebrow='Products' title='Product ecosystem' sub='Hydroforce is currently in progress as a field app for Hydrovac crews and companies.'/><div className='grid gap-5 md:grid-cols-2'><ProductCard title='Hydroforce (In Progress)' text='Field workflow app for Hydrovac dispatch, crew coordination, and reporting.'/><ProductCard title='Northfield Sites' text='Website as a Service productized platform with monthly growth iterations.'/></div></section>
    <section className='section container-wrap'><SectionHeader eyebrow='Proof' title='Early outcomes and execution quality' sub='We focus on practical wins, not vanity design.'/><div className='grid gap-5 md:grid-cols-3'><TestimonialCard quote='Northfield transformed our online presence into a serious sales asset.' who='Local service company'/><TestimonialCard quote='Monthly package gave us momentum without hiring in-house.' who='SMB founder'/><TestimonialCard quote='Design quality finally matches the value we deliver.' who='Operations business'/></div></section>
    <section className='section container-wrap'><SectionHeader eyebrow='Plans' title='Monthly engagement models' sub='No hard pricing here. Scope is tailored to goals and speed.'/><div className='grid gap-5 md:grid-cols-3'><PricingCard title='Starter Site' text='Best for clean relaunches and lead-generation websites.'/><PricingCard title='Growth Engine' text='Best for ongoing conversion and content expansion.'/><PricingCard title='Platform Build' text='Best for product-heavy experiences and integrations.'/></div></section>
    <section className='section container-wrap'><SectionHeader eyebrow='FAQ' title='Questions before you start' sub='Everything you need to know about packages, ownership, and support.'/><FAQAccordion /></section>
  </main>;
}
