import { BackgroundDecor } from '@/components/BackgroundDecor';
import { FAQAccordion } from '@/components/FAQAccordion';
import { Button, FeatureCard, PricingCard, ProductCard, SectionHeader, TestimonialCard } from '@/components/ui';
import { pageMetadata } from '@/lib/seo';

export const metadata = pageMetadata('Velora | Custom Software, SaaS Apps & Business Automation', 'Velora builds custom software, SaaS platforms, CRM systems, dashboards, and automation tools for modern businesses.', '/');

export default function HomePage() {
  return <main className='relative overflow-hidden'><BackgroundDecor />
    <section className='section container-wrap'><div className='grid gap-10 lg:grid-cols-2 lg:items-center'><div><p className='mb-4 text-xs font-semibold uppercase tracking-[0.22em] text-emerald-500'>Velora</p><h1 className='text-5xl font-semibold leading-tight md:text-6xl'>Software systems built for modern businesses.</h1><p className='mt-6 text-lg text-slate-600 dark:text-slate-300'>Velora designs and builds custom apps, SaaS platforms, CRM systems, and automation tools that help businesses move faster, reduce manual work, and operate with clarity.</p><div className='mt-8 flex flex-wrap gap-4'><Button href='/contact'>Book a Demo</Button><Button href='/products' variant='secondary'>Explore Products</Button></div><div className='mt-8 flex gap-6 text-sm text-slate-500'><span>SMB Focused</span><span>Fast Delivery</span><span>Long-term Support</span></div></div><div className='card grid gap-4'><div className='h-28 rounded-xl bg-gradient-to-r from-emerald-500/20 to-cyan-400/20'/><div className='grid gap-4 sm:grid-cols-2'><div className='h-24 rounded-xl border border-slate-200/60 dark:border-slate-700'/><div className='h-24 rounded-xl border border-slate-200/60 dark:border-slate-700'/></div><div className='h-20 rounded-xl border border-slate-200/60 dark:border-slate-700'/></div></div></section>
    <section className='section container-wrap'><SectionHeader eyebrow='Problem' title='Most teams are running critical operations through chaos.' sub='Scattered tools, spreadsheet workflows, manual admin, slow operations, and poor visibility block growth.'/><div className='grid gap-5 md:grid-cols-5'>{['Scattered tools','Spreadsheets','Manual admin','Slow operations','Poor visibility'].map(i=><FeatureCard key={i} title={i} text='Creates delays, errors, and lost revenue opportunities.'/>)}</div></section>
    <section className='section container-wrap'><SectionHeader eyebrow='Solution' title='Velora builds systems that make operations clean and scalable.' sub='Custom software development, SaaS development, CRM systems for small business, and business automation software.'/><div className='grid gap-5 md:grid-cols-3'>{['Custom software','Automation flows','Executive dashboards','CRM systems','Client portals','SaaS platforms'].map(i=><FeatureCard key={i} title={i} text='Built for measurable results and adoption.'/>)}</div></section>
    <section className='section container-wrap'><SectionHeader eyebrow='Products' title='Product ecosystem' sub='Purpose-built systems for modern operators.'/><div className='grid gap-5 md:grid-cols-2'><ProductCard title='HydroOps' text='Operations platform for hydrovac and field service companies.'/><ProductCard title='Velora CRM' text='Internal CRM and client management system.'/><ProductCard title='Dropshipping Research' text='Product research and ecommerce intelligence tool.'/><ProductCard title='Custom Apps' text='Tailored systems for specific businesses.'/></div></section>
    <section className='section container-wrap'><SectionHeader eyebrow='Process' title='A practical 4-step delivery system' sub='Discover, design, build, launch.'/><ol className='grid gap-5 md:grid-cols-4'>{['Discover','Design','Build','Launch'].map(step=><li key={step} className='card font-medium'>{step}</li>)}</ol></section>
    <section className='section container-wrap'><SectionHeader eyebrow='Case studies' title='Proof through shipped outcomes' sub='Selected examples from field service, local business, and ecommerce.'/><div className='grid gap-5 md:grid-cols-3'><TestimonialCard quote='Hydrovac system improved dispatch and daily visibility.' who='Hydrovac operations system'/><TestimonialCard quote='Custom CRM reduced admin time and improved follow-up.' who='Small business CRM'/><TestimonialCard quote='Research tool increased product win rates.' who='Ecommerce product research tool'/></div></section>
    <section className='section container-wrap'><SectionHeader eyebrow='Pricing' title='Engagement models' sub='Flexible packages based on scope and business stage.'/><div className='grid gap-5 md:grid-cols-3'><PricingCard title='Starter Build' text='Launch a focused custom app or workflow.'/><PricingCard title='Growth System' text='Scale automation, CRM, and reporting across teams.'/><PricingCard title='Custom Platform' text='Full platform architecture for multi-team operations.'/></div></section>
    <section className='section container-wrap'><SectionHeader eyebrow='FAQ' title='Answers before we build' sub='Clear expectations for timeline, ownership, and support.'/><FAQAccordion /></section>
    <section className='section container-wrap text-center'><h2 className='text-3xl font-semibold md:text-4xl'>Ready to build the system your business actually needs?</h2><p className='mx-auto mt-4 max-w-2xl text-slate-600 dark:text-slate-300'>Velora is a software company in Canada helping SMB teams build custom web apps with practical pricing and measurable outcomes.</p><div className='mt-8'><Button href='/contact'>Book a Demo</Button></div></section>
  </main>;
}
